language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    # Laravel 5.5
    - php: 7.1
      env: LARAVEL=5.5.* PHPUNIT=~6.0
    - php: 7.2
      env: LARAVEL=5.5.* PHPUNIT=~6.0

    # Laravel 5.6
    - php: 7.1
      env: LARAVEL=5.6.* PHPUNIT=~7.0
    - php: 7.2
      env: LARAVEL=5.6.* PHPUNIT=~7.0

    # Laravel 5.7
    - php: 7.1
      env: LARAVEL=5.7.* PHPUNIT=~7.5
    - php: 7.2
      env: LARAVEL=5.7.* PHPUNIT=~7.5
    - php: 7.3
      env: LARAVEL=5.7.* PHPUNIT=~7.5

    # Laravel 5.8
    - php: 7.1
      env: LARAVEL=5.8.* PHPUNIT=~7.5
    - php: 7.2
      env: LARAVEL=5.8.* PHPUNIT=~8.0
    - php: 7.3
      env: LARAVEL=5.8.* PHPUNIT=~8.0

    # Laravel 6.0
    - php: 7.2
      env: LARAVEL=6.0.* PHPUNIT=~8.0
    - php: 7.3
      env: LARAVEL=6.0.* PHPUNIT=~8.0

before_install:
  - pecl install -f -q pdflib-4.1.3
  - phpenv config-rm xdebug.ini
  - composer self-update --stable --no-interaction

install:
  - travis_retry composer install --no-suggest --no-interaction

script:
  - vendor/bin/phpunit --verbose --configuration phpunit.xml.dist