name: Run tests

on:
  push:
  pull_request:

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [ {version: 8.2, pdflib: php-820}, {version: 8.3, pdflib: php-830}, {version: 8.4, pdflib: php-840} ]
        laravel: [12, 11]
        dependency-version: [prefer-stable]
        os: [ubuntu-latest]
        include:
          - laravel: 12
            testbench: 10.*
          - laravel: 11
            testbench: 9.*

    name: PHP${{ matrix.php.version }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependency-cache-laravel-${{ matrix.laravel }}-php-${{ matrix.php.version }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php.version }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, mysql, pdo_mysql, bcmath, intl, gd, exif, iconv
          ini-values: extension=php_pdflib.so
          coverage: none

      - name: Download PDFlib PHP extension ZIP
        run: >-
          wget -q
          https://www.pdflib.com/binaries/PDFlib/1003/PDFlib-10.0.3p2-Linux-x64-php.tar.gz

      - name: Unpack downloaded PDFlib PHP extension ZIP
        run: tar zxf PDFlib-10.0.3p2-Linux-x64-php.tar.gz

      - name: Copy PDFlib PHP extension to PHP extension directory
        run: >-
          sudo cp
          PDFlib-10.0.3p2-Linux-x64-php/bind/php/${{ matrix.php.pdflib }}-nts/php_pdflib.so
          $(php-config --extension-dir)

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}.*" "orchestra/testbench:${{ matrix.testbench }}"  --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit --testdox --configuration phpunit.xml.dist